/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PropagationHeader is the wire header carrying routing decisions. Always
// W3C Baggage. The actual *member key* used inside the header is per
// ContextRoute — see ContextRouteSpec.RoutingKey / EffectiveRoutingKey().
const PropagationHeader = "baggage"

// TargetReference identifies the Service that a route attaches to (the
// Gateway API parentRef in GAMMA terms). Mirrors the shape commonly used
// across Gateway API extensions so that fields like Namespace / Port can
// be added later without breaking the spec.
type TargetReference struct {
	// Service is the target Service. Same-namespace only for now.
	// +required
	Service ServiceReference `json:"service"`
}

// ServiceReference is a minimal reference to a Service. Designed to be
// extensible — additional fields (port, namespace, group) may be added
// later without breaking existing manifests.
type ServiceReference struct {
	// Name is the Service name in the same namespace as the parent CR.
	// +kubebuilder:validation:MinLength=1
	// +required
	Name string `json:"name"`
}

// VariantSelector selects the candidate Services that traffic to the
// target Service may be diverted to, based on a Baggage member.
type VariantSelector struct {
	// Selector is a label selector applied to Services in the same namespace.
	// Each matched Service contributes one routing rule on the target's
	// HTTPRoute that fires when the Baggage header contains
	// "x-route-prism=<that-service-name>".
	// +required
	Selector metav1.LabelSelector `json:"selector"`
}

// ContextRouteSpec defines the desired state of ContextRoute.
//
// The controller emits a single HTTPRoute attached to the target Service.
// The HTTPRoute carries one rule per matched variant ("if Baggage names
// this variant, send the request to it") plus a catch-all rule that sends
// unmarked traffic back to the target Service itself.
type ContextRouteSpec struct {
	// Target is the Service that receives external/internal traffic and
	// from which routing decisions are made. The HTTPRoute generated by
	// this ContextRoute attaches to this Service via parentRef.
	// +required
	Target TargetReference `json:"target"`

	// Variants are the alternate Services traffic may be diverted to,
	// selected by their Service name appearing in the Baggage member
	// "<routingKey>=<service-name>".
	// +required
	Variants VariantSelector `json:"variants"`

	// RoutingKey is the Baggage member key (and cookie-syntax key) this
	// ContextRoute matches against. When omitted, defaults to
	// "<namespace>.<target.service.name>" — guaranteed cluster-unique by
	// Service identity. Manual values are allowed but the operator runs
	// cross-namespace conflict detection: any two ContextRoutes whose
	// effective RoutingKey collide land both in Ready=False/RoutingKeyConflict
	// (older creationTimestamp wins).
	//
	// Naming rules:
	//   - Must be a valid Baggage member key per W3C: token chars only
	//     (alphanum, `.`, `-`, `_`). The default form `<ns>.<svc>` already
	//     satisfies this because Kubernetes namespace and service names
	//     are themselves DNS labels.
	//   - User-provided values that match the `<existing-ns>.<existing-svc>`
	//     pattern of *another* ContextRoute's effective key collide and
	//     are rejected via the Ready condition.
	// +optional
	RoutingKey string `json:"routingKey,omitempty"`
}

// EffectiveRoutingKey returns the routing key actually used at runtime:
// the explicitly-set Spec.RoutingKey when non-empty, otherwise the default
// "<namespace>.<target-service-name>". Safe to call on a freshly fetched
// CR before defaulting; both branches return a non-empty string when the
// CR is structurally valid (target service name is required by CRD).
func (cr *ContextRoute) EffectiveRoutingKey() string {
	if cr.Spec.RoutingKey != "" {
		return cr.Spec.RoutingKey
	}
	return cr.Namespace + "." + cr.Spec.Target.Service.Name
}

// ConflictRef records that another ContextRoute owns the same target.
type ConflictRef struct {
	// Service is the contested target Service name.
	Service string `json:"service"`
	// OwnedBy is the winning ContextRoute (oldest creationTimestamp).
	OwnedBy string `json:"ownedBy"`
}

// ContextRouteStatus defines the observed state of ContextRoute.
type ContextRouteStatus struct {
	// TargetService is the resolved target Service name (echo of spec).
	// +optional
	TargetService string `json:"targetService,omitempty"`

	// MatchedVariants is the number of variant Services currently selected.
	// +optional
	MatchedVariants int32 `json:"matchedVariants"`

	// VariantServices lists the variant Service names that produced rules.
	// +optional
	VariantServices []string `json:"variantServices,omitempty"`

	// Conflict, if non-nil, indicates another ContextRoute owns the target.
	// +optional
	Conflict *ConflictRef `json:"conflict,omitempty"`

	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=cr
// +kubebuilder:printcolumn:name="Target",type=string,JSONPath=`.spec.target.service.name`
// +kubebuilder:printcolumn:name="Variants",type=integer,JSONPath=`.status.matchedVariants`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// ContextRoute is the Schema for the contextroutes API.
type ContextRoute struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec ContextRouteSpec `json:"spec"`

	// +optional
	Status ContextRouteStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type ContextRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []ContextRoute `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ContextRoute{}, &ContextRouteList{})
}
