//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConflictRef) DeepCopyInto(out *ConflictRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConflictRef.
func (in *ConflictRef) DeepCopy() *ConflictRef {
	if in == nil {
		return nil
	}
	out := new(ConflictRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRoute) DeepCopyInto(out *ContextRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRoute.
func (in *ContextRoute) DeepCopy() *ContextRoute {
	if in == nil {
		return nil
	}
	out := new(ContextRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContextRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRouteList) DeepCopyInto(out *ContextRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContextRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRouteList.
func (in *ContextRouteList) DeepCopy() *ContextRouteList {
	if in == nil {
		return nil
	}
	out := new(ContextRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContextRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRouteSpec) DeepCopyInto(out *ContextRouteSpec) {
	*out = *in
	out.Target = in.Target
	in.Variants.DeepCopyInto(&out.Variants)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRouteSpec.
func (in *ContextRouteSpec) DeepCopy() *ContextRouteSpec {
	if in == nil {
		return nil
	}
	out := new(ContextRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRouteStatus) DeepCopyInto(out *ContextRouteStatus) {
	*out = *in
	if in.VariantServices != nil {
		in, out := &in.VariantServices, &out.VariantServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conflict != nil {
		in, out := &in.Conflict, &out.Conflict
		*out = new(ConflictRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRouteStatus.
func (in *ContextRouteStatus) DeepCopy() *ContextRouteStatus {
	if in == nil {
		return nil
	}
	out := new(ContextRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CookieMatch) DeepCopyInto(out *CookieMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CookieMatch.
func (in *CookieMatch) DeepCopy() *CookieMatch {
	if in == nil {
		return nil
	}
	out := new(CookieMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeTransformation) DeepCopyInto(out *EdgeTransformation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeTransformation.
func (in *EdgeTransformation) DeepCopy() *EdgeTransformation {
	if in == nil {
		return nil
	}
	out := new(EdgeTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeTransformation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeTransformationList) DeepCopyInto(out *EdgeTransformationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EdgeTransformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeTransformationList.
func (in *EdgeTransformationList) DeepCopy() *EdgeTransformationList {
	if in == nil {
		return nil
	}
	out := new(EdgeTransformationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeTransformationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeTransformationSpec) DeepCopyInto(out *EdgeTransformationSpec) {
	*out = *in
	out.Target = in.Target
	if in.WidgetInjection != nil {
		in, out := &in.WidgetInjection, &out.WidgetInjection
		*out = new(WidgetInjectionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeTransformationSpec.
func (in *EdgeTransformationSpec) DeepCopy() *EdgeTransformationSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeTransformationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeTransformationStatus) DeepCopyInto(out *EdgeTransformationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeTransformationStatus.
func (in *EdgeTransformationStatus) DeepCopy() *EdgeTransformationStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeTransformationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderMatch) DeepCopyInto(out *HeaderMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderMatch.
func (in *HeaderMatch) DeepCopy() *HeaderMatch {
	if in == nil {
		return nil
	}
	out := new(HeaderMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariantSelector) DeepCopyInto(out *VariantSelector) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariantSelector.
func (in *VariantSelector) DeepCopy() *VariantSelector {
	if in == nil {
		return nil
	}
	out := new(VariantSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetHTTPSpec) DeepCopyInto(out *WidgetHTTPSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetHTTPSpec.
func (in *WidgetHTTPSpec) DeepCopy() *WidgetHTTPSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetHTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetHotkeySpec) DeepCopyInto(out *WidgetHotkeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetHotkeySpec.
func (in *WidgetHotkeySpec) DeepCopy() *WidgetHotkeySpec {
	if in == nil {
		return nil
	}
	out := new(WidgetHotkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetInjectionSpec) DeepCopyInto(out *WidgetInjectionSpec) {
	*out = *in
	out.HTTP = in.HTTP
	in.Target.DeepCopyInto(&out.Target)
	out.Style = in.Style
	out.JS = in.JS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetInjectionSpec.
func (in *WidgetInjectionSpec) DeepCopy() *WidgetInjectionSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetInjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetJSOverride) DeepCopyInto(out *WidgetJSOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetJSOverride.
func (in *WidgetJSOverride) DeepCopy() *WidgetJSOverride {
	if in == nil {
		return nil
	}
	out := new(WidgetJSOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetJSSpec) DeepCopyInto(out *WidgetJSSpec) {
	*out = *in
	out.Fetch = in.Fetch
	out.XMLHttpRequest = in.XMLHttpRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetJSSpec.
func (in *WidgetJSSpec) DeepCopy() *WidgetJSSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetJSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetMarginSpec) DeepCopyInto(out *WidgetMarginSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetMarginSpec.
func (in *WidgetMarginSpec) DeepCopy() *WidgetMarginSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetMarginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetMatchSpec) DeepCopyInto(out *WidgetMatchSpec) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]HeaderMatch, len(*in))
		copy(*out, *in)
	}
	if in.Cookies != nil {
		in, out := &in.Cookies, &out.Cookies
		*out = make([]CookieMatch, len(*in))
		copy(*out, *in)
	}
	if in.PathPrefixes != nil {
		in, out := &in.PathPrefixes, &out.PathPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetMatchSpec.
func (in *WidgetMatchSpec) DeepCopy() *WidgetMatchSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetMatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetStyleSpec) DeepCopyInto(out *WidgetStyleSpec) {
	*out = *in
	out.Margin = in.Margin
	out.Hotkey = in.Hotkey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetStyleSpec.
func (in *WidgetStyleSpec) DeepCopy() *WidgetStyleSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetStyleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetTargetSpec) DeepCopyInto(out *WidgetTargetSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetTargetSpec.
func (in *WidgetTargetSpec) DeepCopy() *WidgetTargetSpec {
	if in == nil {
		return nil
	}
	out := new(WidgetTargetSpec)
	in.DeepCopyInto(out)
	return out
}
